### PR TITLE
enable shellcheck tests on travis CI. A very nice check tool.

### PR DESCRIPTION
**Pull request by angelabriel**
Change the shell scripts to fullfill the shellcheck requirement.
Found 1 real error and 1 miss in my coding (a realy rarly used condition) during the tests of the shellcheck changes.
Improve the log messages for the kernel.sem settings

### CODE REVIEW

**Comment by diegoakechi** [comment]
Hi @angelabriel,
Very much appreciated. Why did you disable the checks for some variables?

**Review by diegoakechi — APPROVED** [review]
Very good to have it.

**Comment by angelabriel** [comment]
Hi Diego,

I disabled only very few variables, where it was to dangerous or to much work to change and test the effects. In the documentation of the shellcheck tests this was explicitly mentioned as a possible way.
Do you see any problem with that?

**Comment by diegoakechi** [comment]
@angelabriel No, curiosity =)

I just merged it.

**Comment by angelabriel** [comment]
I'm unable to enable travis for the SUSE/sapconf repo. In the travis docu I found the hint
'Note: You can only enable Travis CI builds for repositories you have admin access to.'
Seams that only a person with admin rights to the github repository can enable the repo on travis 
Do you have a chance to enable it or should I ask Duncan?

**Comment by angelabriel** [comment]
forget the last question. Seams it's enabled automatically after some time. I was to eager :-)

**Pull request merged**
